name: Bug Report
description: Report a bug in Material You NewTab.
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with **Material You NewTab**!  
        Before submitting, please check if the issue already exists in the [issues list](https://github.com/XengShi/materialYouNewTab/issues).  
        If you need help, feel free to ask in our [Telegram support group](https://t.me/+i-ekvlM7yoU1Yjc1).  
        Make sure to follow our [Contribution Guidelines](https://github.com/XengShi/materialYouNewTab/blob/main/CONTRIBUTING.md).

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more info?
      placeholder: ex. Telegram username or email (optional)
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue clearly. Also, tell us what you expected to happen.
      placeholder: Describe the bug and expected behavior.
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of Material You NewTab are you using?
      options:
        - Latest stable release
        - Beta/Preview version
        - Manually built from source
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you using?
      multiple: true
      options:
        - Google Chrome
        - Mozilla Firefox
        - Microsoft Edge
        - Brave
        - Opera
        - Other (mention below)

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: Mention your browser version (e.g., Chrome 122.0.0).
      placeholder: ex. Chrome 122.0.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      placeholder: ex. Windows 10, macOS 14, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce the bug step by step.
      placeholder: |
        1. Open the new tab
        2. Enable a feature
        3. See the error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Errors / Logs
      description: If applicable, provide any console errors or logs. (Open DevTools → Console and copy errors)
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, attach screenshots or screen recordings of the bug.

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue, you agree to follow the project's [Code of Conduct](https://github.com/XengShi/materialYouNewTab/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I have searched for duplicate issues and checked the FAQs.
          required: true
        - label: I agree to follow this project's Code of Conduct.
          required: true